#!/bin/bash

pushd()
{
    dirname=$1
    first_symbol=${dirname:0:1}
    if cd ${dirname:?"missing directory name."}
    then 
        DIR_STACK="$PWD $DIR_STACK"
        echo "$DIR_STACK" 
    fi       
}
popd()
{
    DIR_STACK=${DIR_STACK:?"Stack empty."} 
    DIR_STACK=${DIR_STACK#* }
    cd ${DIR_STACK%% *}
    echo "$DIR_STACK"
}
showd()
{
    echo "$DIR_STACK"
}
echo "hello all"